-- Run this in Supabase SQL Editor to create the remaining tables

CREATE TABLE IF NOT EXISTS contact_settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  phone TEXT,
  email TEXT,
  address TEXT,
  google_maps_iframe TEXT,
  facebook_url TEXT,
  instagram_url TEXT,
  linkedin_url TEXT,
  twitter_url TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT one_row_only CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS seo_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page TEXT UNIQUE NOT NULL,
  meta_title TEXT,
  meta_description TEXT,
  keywords TEXT,
  og_image TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS media_library (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name TEXT NOT NULL,
  file_url TEXT NOT NULL,
  file_type TEXT,
  uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure storage bucket exists (Requires postgres admin rights, but typically works in Supabase SQL editor)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('media', 'media', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
CREATE POLICY "Public media access" ON storage.objects FOR SELECT USING (bucket_id = 'media');
CREATE POLICY "Admin media upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'media' AND auth.role() = 'authenticated');
CREATE POLICY "Admin media update" ON storage.objects FOR UPDATE USING (bucket_id = 'media' AND auth.role() = 'authenticated');
CREATE POLICY "Admin media delete" ON storage.objects FOR DELETE USING (bucket_id = 'media' AND auth.role() = 'authenticated');

-- Enable RLS on tables
ALTER TABLE contact_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_library ENABLE ROW LEVEL SECURITY;

-- Public policies
CREATE POLICY "Public Read Settings" ON contact_settings FOR SELECT USING (true);
CREATE POLICY "Public Read SEO" ON seo_settings FOR SELECT USING (true);
CREATE POLICY "Public Read Media" ON media_library FOR SELECT USING (true);

-- Admin policies
CREATE POLICY "Admin All Settings" ON contact_settings FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All SEO" ON seo_settings FOR ALL TO authenticated USING (true);
CREATE POLICY "Admin All Media" ON media_library FOR ALL TO authenticated USING (true);

-- Insert defaults
INSERT INTO contact_settings (id, email, phone) VALUES (1, 'contact@repute.in', '+91 1234567890') ON CONFLICT DO NOTHING;
