-- 1. Create site_pages table
CREATE TABLE IF NOT EXISTS site_pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create site_sections table
CREATE TABLE IF NOT EXISTS site_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_slug TEXT NOT NULL,
  section_name TEXT NOT NULL,
  section_type TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  content JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create site_settings table (if you need it later)
CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key TEXT UNIQUE NOT NULL,
  setting_value TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS) - Recommended
ALTER TABLE site_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

-- 5. Create basic policies (Allow anyone to read, but only authenticated users to write)
-- Note: Replace 'authenticated' with your actual auth setup if different
CREATE POLICY "Public Read Pages" ON site_pages FOR SELECT USING (true);
CREATE POLICY "Admin Update Pages" ON site_pages FOR ALL TO authenticated USING (true);

CREATE POLICY "Public Read Sections" ON site_sections FOR SELECT USING (true);
CREATE POLICY "Admin Update Sections" ON site_sections FOR ALL TO authenticated USING (true);

CREATE POLICY "Public Read Settings" ON site_settings FOR SELECT USING (true);
CREATE POLICY "Admin Update Settings" ON site_settings FOR ALL TO authenticated USING (true);

-- 6. Insert default Home Page entry
INSERT INTO site_pages (slug, title) 
VALUES ('home', 'Home Page')
ON CONFLICT (slug) DO NOTHING;
